Fix "appstream-missing-developer-name" in flathub
goldendict/goldendict pull request #1690
Opened 2024-03-01 11:19 UTC by proletarius101

Flathub now requires the metainfo file to include the developer name: https://docs.flathub.org/docs/for-app-authors/linter#appstream-missing-developer-name

2024-03-01 11:30 UTC, vedgy requested changes

2024-03-01 11:30 UTC, vedgy commented on redist/org.goldendict.GoldenDict.metainfo.xml
> +    <name>GoldenDict</name>
From https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer:

> Values might be for example "The GNOME Foundation" or "The KDE Community".

Maybe "GoldenDict developers"?

2024-03-01 11:30 UTC, vedgy commented on redist/org.goldendict.GoldenDict.metainfo.xml
> +  <developer>
Looks like the `developer` tag was introduced in AppStream 1.0 released [a few months ago](https://blog.tenstral.net/2023/11/appstream-1-0-released.html). Would the new tag be a problem for distros that package an older version of AppStream? If yes, maybe use the older deprecated `<developer_name> ` tag for the time being?

2024-03-01 13:27 UTC, vedgy commented
@Abs62, OK if I squash the two commits into one and merge?

2024-03-01 13:28 UTC, vedgy approved these changes

2024-03-01 14:10 UTC, Abs62 commented
@vedgy, OK.

2024-03-01 17:49 UTC, vedgy commented
@proletarius101, do you want to use the users.noreply.github.com email address for the commit? If not, please squash the two commits, update the author email address and force-push.

2024-03-02 14:50 UTC, vedgy commented
@proletarius101, the commit author email is still @users.noreply.github.com. You can use `git commit --amend --author="..."` to override it.

2024-03-03 17:28 UTC, closed without merging

2024-03-03 17:30 UTC, vedgy commented
Merged as c38d39a467a612bfb63bb704799972c30fb7b993.